name: Combine PRs

on:
  schedule:
    - cron: '0 0 * * *' # Every day at 00:00 UTC
  workflow_dispatch:

jobs:
  combine-prs:
    if: github.repository == 'junit-team/junit5'
    runs-on: ubuntu-latest
    steps:
      - name: combine-prs
        uses: github/combine-prs@v3.1.1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
