name: "Validate Gradle Wrapper"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
